version: "3.8"

services:
  cowrie:
    image: cowrie/cowrie:latest
    container_name: cowrie
    restart: unless-stopped
    ports:
      - "22:2222"   # SSH: host 22 -> container 2222
      - "23:2223"   # Telnet: host 23 -> container 2223 (可选)
    volumes:
      - ./data/cowrie/var:/cowrie/var   # 持久化日志与下载
    # 可按需设置时区：
    # environment:
    #   - TZ=Asia/Shanghai
